### PR TITLE
Implement dialog

### LINKED ISSUE #12: Add a modal dialog
This is intended to be used by all of the Jupyter repos, but I am prototyping it here.
The dialog will present as a transparent div encompassing the `host` node.

``` typescript
/**
 * A button applied to a dialog.
 */
export
interface IButtonItem {
  /**
   * The text for the button.
   */
  text: string;

  /**
   * The icon class for the button.
   */
  icon?: string;

  /**
   * The extra class name to associate with the button.
   */
  className?: string;

  /**
   * The command for the button.
   */
  command?: ICommand;

  /**
   * The args object for the button command.
   */
  commandArgs?: any;
}


/**
 * Define a default "OK" button.
 */
export
const okButton: IButtonItem = {
  text: 'OK',
  className: 'jp-Dialog-ok-button'
}


/**
 * Define a default "Cancel" button.
 */
export
const cancelButton: IButtonItem = {
  text: 'Cancel',
  className: 'jp-Dialog-cancel-button'
}


/**
 * An implementation of a modal dialog.
 */
export
class Dialog {
  /**
   * Create a dialog and show it.
   */
  static showDialog(title: string, host: HTMLElement, body: HTMLElement, buttons?: IButtonItem[]): Promise<IButtonItem>{ }

  /**
   * Construct a new dialog.
   */
  constructor(title: string, host: HTMLElement, body: HTMLElement, buttons?: IButtonItem[]) {
    this._title = title;
    this._host = host;
    this._body = body;
    this._buttons = buttons || [okButton, cancelButton];
  }

  /**
   * Show the dialog over the host node.
   *
   * @returns The button item that was selected or `null` if the dialog was Escaped.
   */
  show(): Promise<IButtonItem> { }
}
```

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #12.
Uses https://github.com/blink1073/phosphor-dialog/tree/initial for now.

dialog_demo

### CODE REVIEW

**Comment by blink1073** [comment]
@ellisonbg, @jasongrout, should we make a new repo for this, such as `jupyter-js-dialog`?

**Comment by blink1073** [comment]
Nevermind, we decided to create https://github.com/phosphorjs/phosphor-dialog for this.

**Comment by ellisonbg** [comment]
+1 on that being in phosphor

**Comment by dwillmer** [comment]
:+1:

**Pull request merged**
