### PR TITLE
Fix icon colours

### PR DESCRIPTION
**Pull request by dwillmer**

### CODE REVIEW

**Comment by blink1073** [comment]
Hmm, this highlights the fact that we should be using another class for this and adding it in CSS, care to take that on?

**Comment by sccolbert** [comment]
you don't need another class. That's what selectors are for.

**Comment by sccolbert** [comment]
unless you're talking about the drop icon?

**Comment by blink1073** [comment]
Ah, yeah, we should use one for the drop icon, and move the icon style color to css.

**Comment by blink1073** [comment]
LGTM, thanks.

**Pull request merged**
