### PR TITLE
Update styling

### LINKED ISSUE #99: Style fixes
Make the current column header bold.
Make the column splitter full height.

### PR DESCRIPTION
**Pull request by blink1073**
filebrowser-styling

Fixes #99.

### CODE REVIEW

**Comment by dwillmer** [comment]
LGTM

**Comment by blink1073** [comment]
@cameronoelsen, thoughts on this?  I couldn't find a specified color for hover state, and have not yet added click state.  Did you want to have the table headers show hover state?

**Comment by blink1073** [comment]
Also, what should the hover behavior of selected file items be?

**Comment by cameronoelsen** [comment]
@blink1073 There shouldn't be a hover state for the table header, and I think that the hover behavior of the table items below should be full width like you are showing above. I am going to detail the amount of margin and padding for each item soon. I am currently working on the menu flyouts for the top navbar. I will make this my priority after making those mockups

**Comment by blink1073** [comment]
Great, thanks!  I removed the hover color from the header.

**Pull request merged**
