### PR TITLE
Add Buttons

### PR DESCRIPTION
**Pull request by blink1073**
filebrowser_demo2

### CODE REVIEW

**Comment by blink1073** [comment]
Right now refresh is the only functional button.

**Comment by blink1073** [comment]
filebrowser_demo3

**Comment by blink1073** [comment]
I'll save the upload implementation for the next PR, since that will be pretty involved.

**Comment by blink1073** [comment]
Updated buttons:

screen shot 2015-12-10 at 2 40 10 pm

**Comment by dwillmer** [comment]
:+1:

**Pull request merged**
